spring:
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
    timeout: 1800
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:8000/lexly_database
    username: postgres
    password: IKER1234
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres
server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
paypal:
  mode: sandbox
  client:
    id: ASH-5W4rF097Wr96eqw-XHStDs7pZyRPz4cNihmr4dbUlBQEjTN-9-hBKjK3xgsFAWwifrHY10dbPBG_
    secret: EI-c8_-WM9UHSZdBGqzZNobFbpyZ_AnbMtl_4pWtlyZL13yhgAa0liPcDT5vMnqOPImhFaUWSlT8DFKN
  base:
    url: "https://api-m.sandbox.paypal.com"
app:
  firebase-configuration-file: docura-fbcf0-firebase-adminsdk-flaal-99a8fba29f.json
  secret-key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
my-custom-cookie-name: "MyCookie"

