spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/lexly_database
    username: postgres
    password: password
  driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres

server:
  port: 8081
paypal:
  mode: sandbox
  client:
    id: AYSq3RDGsmBLJE-otTkBtM-jBRd1TCQwFf9RGfwddNXWz0uFU9ztymylOhRS
    secret: EGnHDxD_qRPdaLdZz8iCr8N7_MzF-YHPTkjs6NKYQvQSBngp4PTTVWkPZRbL

app:
  firebase-configuration-file: docura-fbcf0-firebase-adminsdk-flaal-99a8fba29f.json
