spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/lexly_database
    username: postgres
    password: password
  driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres

server:
  port: 8080
stripe:
  apiKey: pk_test_51O9UVfD5LDSReTo56PZNsG68UYoHrrpO39FvPe2hBCY9UGNZzvhg5QGcLaqPLKVI7lItLUHjMDX5XGMz3j33WgNK008t7YmrD0
